# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Peterson Santos
email: hello@petersonfs.me
description: > # I work at ateliware, a software boutique from Curitiba - Brazil, that helps startups and enterprise to deliver amazing products and solutions. I often share my thoughts on twitter, write detailed here and share my code at github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://petersonfs.me" # the base hostname & protocol for your site
twitter_username: petersonfs
github_username:  petersonfs

# Build settings
markdown: kramdown
