title: Peterson Santos
name: Peterson Santos
email: hello@petersonfs.me
description: > # I work at ateliware, a software boutique from Curitiba - Brazil, that helps startups and enterprise to deliver amazing products and solutions. I often share my thoughts on twitter, write detailed here and share my code at github.
baseurl: ""
url: "http://petersonfs.me"
twitter_username: petersonfs
github_username:  petersonfs
markdown: kramdown
kramdown:
  input: GFM
gems:
  - octopress-autoprefixer
